---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neoai-ide-deployment
  labels:
    app: neoai-ide
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neoai-ide
  template:
    metadata:
      labels:
        app: neoai-ide
    spec:
      containers:
        - name: neoai-ide-container
          image: shekharpatnaik/neoai-ide:0.14
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_URL
              value: "https://neoai-ide.shekharpatnaik.uk"  # Replace with your domain
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextjs-secrets
                  key: NEXTAUTH_SECRET
            - name: GITLAB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: nextjs-secrets
                  key: GITLAB_CLIENT_ID
            - name: GITLAB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextjs-secrets
                  key: GITLAB_CLIENT_SECRET
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nextjs-secrets
                  key: ANTHROPIC_API_KEY
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: nextjs-secrets
                  key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: neoai-ide-service
  labels:
    app: neoai-ide
spec:
  type: ClusterIP
  selector:
    app: neoai-ide
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neoai-ide-ingress
  annotations:
    kubernetes.io/ingress.class: nginx            # Adjust if using a different ingress controller
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - neoai-ide.shekharpatnaik.uk
      secretName: shekharpatnaik-uk-tls
  rules:
    - host: neoai-ide.shekharpatnaik.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neoai-ide-service
                port:
                  number: 80
